name: sim_ws
root: ~/sim_ws

windows:
  - dev_abuse:
      layout: main-vertical
      panes:
        - shell:
          - sleep 10
          - yarn shell
        - up:
          - yarn up
        - odom_to_tf:
          - sleep 10
          - yarn shell
          - rosrun social_sim_ros odom_to_tf.py
        - move_base:
          - sleep 10
          - yarn shell
          - roslaunch --wait social_sim_ros jackal_move_base.launch
        - rqt_graph:
          - sleep 10
          - yarn shell
          - rqt_graph
        - description:
          - sleep 10
          - yarn shell
          - roslaunch --wait social_sim_ros jackal_description.launch
        - differential_drive:
          - sleep 10
          - yarn shell
          - roslaunch --wait social_sim_ros differential_drive_jackal.launch
        - gmapping:
          - sleep 10
          - yarn shell
          - roslaunch --wait social_sim_ros gmapping_jackal.launch
        - viz:
          - sleep 10
          - yarn shell
          - rosrun rviz rviz -d $(rospack find social_sim_ros)/config/jackal_move.rviz
        - velodyne:
          - sleep 10
          - yarn shell
          - rosrun nodelet nodelet standalone velodyne_pointcloud/CloudNodelet
        - velodyne_to_scan:
          - sleep 10
          - yarn shell
          - roslaunch social_sim_ros velodyne_to_laser.launch
        #- joy:
        #  - sleep 10
        #  - yarn shell
        #  - roslaunch --wait social_sim_teleop ps3_teleop.launch
