name: ps3joy
root: ~/sim_ws

windows:
  - dev_abuse:
      layout: main-vertical
      panes:
        - shell:
          - printf '\033]2;%s\033\\' 'shell'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
        - up:
          - printf '\033]2;%s\033\\' 'yarn up'
          - yarn up
        - odom_to_tf:
          - printf '\033]2;%s\033\\' 'odom_to_tf.py'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - rosrun social_sim_ros odom_to_tf.py _publish_map_frame:=true
        - joy:
          - printf '\033]2;%s\033\\' 'ps3_joy'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - roslaunch --wait social_sim_teleop ps3_teleop.launch
        - rqt_graph:
          - printf '\033]2;%s\033\\' 'rqt_graph'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - rqt_graph
        - description:
          - printf '\033]2;%s\033\\' 'warthog_description.launch'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - roslaunch --wait social_sim_ros warthog_description.launch
        - differential_drive:
          - printf '\033]2;%s\033\\' 'differential_drive_warthog.launch'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - roslaunch --wait social_sim_ros differential_drive_warthog.launch
        - map_server:
          - printf '\033]2;%s\033\\' 'outdoor_map_server.launch'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - roslaunch --wait social_sim_ros outdoor_map_server.launch
        - rviz:
          - printf '\033]2;%s\033\\' 'rviz'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - rosrun rviz rviz -d $(rospack find social_sim_ros)/config/jackal_move.rviz
        - velodyne:
          - printf '\033]2;%s\033\\' 'velodyne_pointcloud'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - roslaunch --wait velodyne_pointcloud VLP16_points.launch
        - velodyne_to_scan:
          - printf '\033]2;%s\033\\' 'warthog_velodyne_to_laser'
          - sleep 10
          - yarn shell || echo 'yarn not found. running on host'
          - roslaunch --wait social_sim_ros warthog_velodyne_to_laser.launch
