name: ps3joy
root: ~/sim_ws

windows:
  - dev_abuse:
      layout: main-vertical
      panes:
        - shell:
          - sleep 10
          - yarn shell
        - up:
          - yarn up
        - odom_to_tf:
          - sleep 10
          - yarn shell
          - rosrun social_sim_ros odom_to_tf.py
        - description:
          - sleep 10
          - yarn shell
          - roslaunch --wait social_sim_ros jackal_description.launch
        - differential_drive:
          - sleep 10
          - yarn shell
          - roslaunch --wait social_sim_ros differential_drive_jackal.launch
        - gmapping:
          - sleep 10
          - yarn shell
          - roslaunch --wait social_sim_ros gmapping_jackal.launch
        - viz:
          - sleep 10
          - yarn shell
          - rosrun rviz rviz -d $(rospack find social_sim_ros)/config/jackal_move.rviz
        - trial:
          - sleep 10
          - yarn shell
          - rosrun social_sim_ros trial_runner.py
        - joy:
          - sleep 10
          - yarn shell
          - roslaunch --wait social_sim_teleop ps3_teleop.launch

